language: rust
addons:
  apt:
    packages:
    - libssl-dev
    - musl-tools
cache: cargo
os:
- linux
- osx
rust:
- nightly-2017-12-05
after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
before_deploy: |
  NAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d "/" -f2)
  export NAME
  if [ $TRAVIS_OS_NAME = linux ]
  then
    rustup target add x86_64-unknown-linux-musl && \
    cargo build --release --target x86_64-unknown-linux-musl && \
    zip -j "${NAME}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}".zip target/x86_64-unknown-linux-musl/release/${NAME}
  else
    cargo build --release && \
    zip -j "${NAME}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}".zip target/release/${NAME}
  fi
deploy:
  provider: releases
  api_key:
    secure: Oq49yQiI373YPhUIEXozQo7R+C4U02DV01DWWEc1VScG1Sx4VgEcVEQrcOp6aR5v7Uct1EEyQl/wAQaQmuw2S+p2o7iDM+JqnOG/YBJPdSNaXqMQyvDVDhYnF56u7TKFSUxGAmke2QZZTu3UG6KZGSvKznc97N/azkTFpjbcApy6K8hNPKWqFhhK8W8nFuJeD4MnZaCGRfJXRdnITqc5VRBM3wBQ4zgZZPviN9Sq6y0f1xK2IFwaCKTl/VrCTavHmn59Lq3XcF2NBVdzRbSZJUBd5FTCmnjrZHY9j1YcUXxSKG9H3JMmUbWdqYLcuETQiFd3HxXdeA1mX/TGR6UGSfLrWxAKvHU0+fiy2D4PoubbN3LleI4tu4UxAZu3wpwX5iNx7N+/1M/OngKxZdAmbyjEb+ey3fcc7aD4NMJ2R5oMZWirFzmelTuduSaUfLsnTO2oqRZcQEL/utA3aaYGnJQqUCr+xVb09CQ8/h7ClsEj7ydt5KLL9qAMsoLbQxXBwNNCCpdVw6vuIfJ80ncblqzQF86a65arvQlKWdFjVbOK2IqhHDatbsZ41Ahp6nCrWUGoSVCF8N9lrRwWjd9IYxD+asQ851Lc/Bz/FJVEJJJzqLXpC4K3ZBBq5GHh9f2eeeQTyly3nAZk8lILfaik7lVheag3oLUfxSzmk7TRUKY=
  file_glob: true
  file: "${NAME}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    tags: true
